<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.15" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.15" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ITJobs.Entities\ITJobs.Entities.csproj" />
    <ProjectReference Include="..\ITJobs.Infrastructure.Commons\ITJobs.Infrastructure.Commons.csproj" />
    <ProjectReference Include="..\ITJobs.UseCases\ITJobs.UseCases.csproj" />
  </ItemGroup>

</Project>
